### PR TITLE
Doc: Use debug_file with sshd and SELinux

### LINKED ISSUE #195: debug with sshd requires SELinux permission
This should probably be mentioned somewhere in the docs:
`debug` and `debug_file` does not work in SSH+PAM scenario unless SELinux allows sshd to open the file (I have not found the related sebool yet, I just set SELinux to permissive and it starts working). Took me a while to realize.

### PR DESCRIPTION
**Pull request by zypA13510**
Close #195.

### CODE REVIEW

**Comment by zypA13510** [comment]
**Note:** the file has been renamed as this applies not only to Fedora but Enterprise Linux too.

**Comment by klali** [comment]
As you can see this failed to build since the name of the document needs to be correct in Makefile.am can you fix that?

**Comment by zypA13510** [comment]
Done.

**Comment by klali** [comment]
Thanks!

**Pull request merged**
